### ISSUE TITLE
One or more undefined variables: 'host' is undefined

### ISSUE THREAD

**Issue by gregorskii** [weareinteractive/ansible-ssh#3]
Hi there,

This error is being thrown by the "bfmartin.ssh_known_hosts | Manage ssh_known_hosts file" but the host value is coming from the known_hosts.yml task in this plugin.

It appears that the bfmartin package is being passed an empty host value.

Here is the playbook:

```

---
- hosts: all
  sudo: yes
  roles:
    - franklinkim.apt
    - franklinkim.timezone
    - franklinkim.users
    #- franklinkim.users-oh-my-zsh
    - franklinkim.sudo
    - franklinkim.ssh
  vars_files:
    - vars/ssh.yml
    - vars/users.yml
    - vars/apt.yml
  vars:
    timezone: 'America/Los Angeles'

```

vars_file .ssh:

```

---
ssh_port:
  - 22
ssh_permit_root_login: 'no'
ssh_pubkey_authentication: 'yes'
ssh_password_authentication: 'yes'
ssh_known_hosts:
  - github.com

```

I have also tried:

```

---
ssh_port:
  - 22
ssh_permit_root_login: 'no'
ssh_pubkey_authentication: 'yes'
ssh_password_authentication: 'yes'
ssh_known_hosts: []

```

As I do not really need any known hosts at this time.

Thank you for any help you can provide.
