### ISSUE TITLE
ssh_known_hosts blocks

### ISSUE THREAD

**Issue by cryptolukas** [weareinteractive/ansible-ssh#6]
I get errors for undefined values and I don't able to fix it.

``` 
ansible 2.7.1
config file = /etc/ansible/ansible.cfg
configured module search path = [u'/home/lukas/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python2.7/dist-packages/ansible
executable location = /usr/bin/ansible
python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

Playbook
```
- hosts: all
  roles:
    - mrlesmithjr.chrony
    - franklinkim.ssh
  vars:
    chrony_local_stratum: 10
    chrony_ntp_servers:
      - server: 'time.google.com'
        options:
        - option: 'iburst'
        - option: 'minpoll'
          val: 8
      - server: '0.de.pool.ntp.org'
        options:
        - option: 'iburst'
        - option: 'minpoll'
          val: 8
      - server: '0.fr.pool.ntp.org'
        options:
        - option: 'iburst'
        - option: 'minpoll'
          val: 8
      - server: '0.at.pool.ntp.org'
        options:
        - option: 'iburst'
        - option: 'minpoll'
          val: 8
    ssh_password_authentication: 'no'
```

Ouput

```
PLAY [all] **********************************************************************************************************************************************************************************
TASK [Gathering Facts] **********************************************************************************************************************************************************************
ok: [host.example.de]
TASK [mrlesmithjr.chrony : debian | Installing Chrony] **************************************************************************************************************************************
ok: [host.example.de]
TASK [mrlesmithjr.chrony : config_chrony | Configuring Chrony] ******************************************************************************************************************************
ok: [host.example.de]
TASK [franklinkim.ssh : Installing packages] ************************************************************************************************************************************************
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via squash_actions is deprecated. Instead of using a loop to supply multiple items and specifying `pkg: {{ item }}`, 
please use `pkg: [u'openssh-server', u'openssh-client']` and remove the loop. This feature will be removed in version 2.11. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
ok: [host.example.de] => (item=[u'openssh-server', u'openssh-client'])
TASK [franklinkim.ssh : Configuring sshd] ***************************************************************************************************************************************************
ok: [host.example.de]
TASK [franklinkim.ssh : Registering known hosts] ********************************************************************************************************************************************
getaddrinfo ssh_known_hosts: Temporary failure in name resolution
failed: [host.example.de] (item=ssh_known_hosts) => {"changed": false, "item": "ssh_known_hosts", "msg": "No key specified when adding a host"}
to retry, use: --limit @/home/lukas/git/ansible/basics.retry
PLAY RECAP **********************************************************************************************************************************************************************************
host.example.de         : ok=5    changed=0    unreachable=0    failed=1   
```
I
