### ISSUE TITLE
Configuration depends on deprecated variables

### ISSUE THREAD

**Issue by goetzk** [weareinteractive/ansible-ssh#9]
Hi,

Some values in head (9c7c6aa2bafffa184732657b4fc9d8fee02643e8) still appear to be populated by the legacy variables while some new settings don't appear to be used.

Controller is Debian 10, targets are Ubuntu 18.04

I'm still not entirely sure whats happening because some legacy variables (ssh_protocol doesn't appear to have an impact) DONT work sooo... not sure.

This configuration
```
ssh_config:
  # Our preferences; note OSCAP recommend no to root
  PermitRootLogin: 'yes'
  PubkeyAuthentication: 'yes'
  PasswordAuthentication: 'no'
  # Defaults:
  ChallengeResponseAuthentication: "no"
  UsePAM: "yes"
  X11Forwarding: "no"
  PrintMotd: "no"
  AcceptEnv: LANG LC_*
  Subsystem: sftp /usr/lib/openssh/sftp-server
  # OSCAP recommendations
  ClientAliveInterval: 300
  ClientAliveCountMax: 0
  # We have an ssh v2 only version, but it fails us anyway...
  Protocol: 2
```

Produces this output
```
# Ansible managed


Subsystem sftp /usr/lib/openssh/sftp-server
PubkeyAuthentication yes
UsePAM yes
PrintMotd no

Port 22

PasswordAuthentication yes
PermitRootLogin yes
AcceptEnv LANG LC_*
X11Forwarding yes
ChallengeResponseAuthentication no
```

Add ssh_password_authentication (with the rest of ssh_config the same)
```
# Managing SSH config per OSCAP
ssh_port: [22]
ssh_protocol: 2
ssh_password_authentication: 'no'
ssh_config:
  # Our preferences; note OSCAP recommend no to root
  [... etc ...]
```
Changes the configuration:
```
+++ after: /home/kgoetz/.ansible/tmp/ansible-local-36635k7Dvt/tmpR3UYxD/sshd_config.j2
@@ -8,7 +8,7 @@
 
 Port 22
 
-PasswordAuthentication yes
+PasswordAuthentication no
 PermitRootLogin yes
 AcceptEnv LANG LC_*
 X11Forwarding yes

changed: [...]
```

Any thoughts on what might be at play here?

thanks
Karl.
